export const ShopImages = {
    food_jail: require('../../assets/shops/the_food_jail.jpeg'),
    fruit_me: require('../../assets/shops/fruit_me_up.jpeg'),
    house_of_pulav: require('../../assets/shops/house_of_pulaos.jpeg'),
    us_pizza: require('../../assets/shops/planet_pizza.jpeg'),
    burma_food: require('../../assets/shops/burma_food_junction.jpeg'),
    dumont: require('../../assets/shops/dumont.jpeg'),
    aa_ruchulu: require('../../assets/shops/aa_ruchulu.jpeg'),
    pub_g: require('../../assets/shops/pubg.jpeg'),
    red_chillis: require('../../assets/shops/red_chillis.jpeg'),
    alpha: require('../../assets/shops/alpha_arabian_food.jpeg'),
    wow_momo: require('../../assets/shops/wow_momo.jpeg'),
    darbar: require('../../assets/shops/darbar.jpeg'),
    punjabi_tadka: require('../../assets/shops/punjabi_tadka.jpeg'),
    varsha_cool_drinks: require('../../assets/shops/varsha_cool_drinks.jpeg'),
    red_bucket: require('../../assets/shops/the_red_bucket_biriyani.jpeg'),
    bawarchi: require('../../assets/shops/bawarchi.jpeg'),
    grills_n_rolls: require('../../assets/shops/grills_and_rolls.jpeg'),
    kfc: require('../../assets/shops/kfc.jpeg'),
    falooda: require('../../assets/shops/punjabi_falooda_kulfi.jpeg'),
    waffle_cafe: require('../../assets/shops/waffle_cafe.jpeg'),
};
